Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider :virtualbox do |v|
    v.name = "focal64"
    v.gui = true
    v.memory = 2048
  end

  config.vm.synced_folder "data", "/home/vagrant/data", create: true, owner: "vagrant", group: "vagrant"

  config.vm.provision "bootstrap", type: "shell", inline: <<-SHELL
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub|sudo apt-key add -
    sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" > /etc/apt/sources.list.d/google.list'

    sudo apt update -y
    sudo apt upgrade -y

    sudo apt install -y --no-install-recommends ubuntu-desktop
    
    sudo apt install -y --no-install-recommends virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
    
    # Add `vagrant` to Administrator
    sudo usermod -a -G sudo vagrant
    
    sudo apt install -y google-chrome-stable transmission
    sudo snap install vlc
  SHELL

  config.vm.provision "updates", type: "shell", run: "always", privileged: false, after: "bootstrap", inline: <<-SHELL
    echo "## Configuring desktop ##"
    gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'es')]"
    gsettings set org.gnome.shell favorite-apps "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'vlc_vlc.desktop', 'transmission-gtk.desktop']"
  
    echo "## Updating packages ##"
    sudo apt update -y
    sudo apt upgrade -y

    echo "## Other stuff ##"
    git config --global user.name "Guillem Mercadal"
    git config --global user.email guillem.mercadal@gmail.com
    
    #sudo chown -R vagrant:vagrant /home/vagrant/data

  SHELL

  config.vm.provision :shell, after: :all, inline: "sudo shutdown -r now"

end
