# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-20.04-desktop-amd64"
  config.vm.box_version = "20220102.01"
  config.vm.synced_folder "data", "/home/vagrant/data", create: true,
  	owner: "vagrant", group: "vagrant"

  # eztv
  # yts-movie	

  config.vm.provider :virtualbox do |vb|
    vb.name = "ubuntu20"
  end

  # Workaround to forward ssh key from Windows Host with Git Bash
  if Vagrant::Util::Platform.windows?
    if File.exists?(File.join(Dir.home, ".ssh", "id_rsa"))
        # Read local machine's SSH Key (~/.ssh/id_rsa)
        ssh_key = File.read(File.join(Dir.home, ".ssh", "id_rsa"))
        # Copy it to VM as the /vagrant/.ssh/id_rsa key
        config.vm.provision :shell, privileged: false, :inline => "echo 'Windows-specific: Copying local SSH Key to VM for provisioning...' && mkdir -p /home/vagrant/.ssh && echo '#{ssh_key}' > /home/vagrant/.ssh/id_rsa && chmod 600 /home/vagrant/.ssh/id_rsa", run: "always"
    else
        # Else, throw a Vagrant Error. Cannot successfully startup on Windows without a SSH Key!
        raise Vagrant::Errors::VagrantError, "\n\nERROR: SSH Key not found at ~/.ssh/id_rsa.\nYou can generate this key manually by running `ssh-keygen` in Git Bash.\n\n"
    end
  end

  # Run a shell script in first run
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    set -euxo pipefail

    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
	sudo sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list'

    APT_GET='sudo DEBIAN_FRONTEND=noninteractive apt-get'

    # Upgrade system
    $APT_GET update
    $APT_GET dist-upgrade -y
    $APT_GET install git google-chrome-stable -y
    $APT_GET autoremove -y
    sudo snap refresh
    sudo snap install vlc

    # Set keyboard layout
    gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'es')]"

    # Set favorite apps
    gsettings set org.gnome.shell favorite-apps "['firefox.desktop', 'google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'vlc_vlc.desktop', 'transmission-gtk.desktop']"

    # Set up git & configurations
    git config --global user.name "Guillem Mercadal"
    git config --global user.email guillem.mercadal@gmail.com
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    rm -fR configurations && git clone git@github.com:akustik/configurations.git

    # Shared folder permissions
    sudo chown -R vagrant:vagrant /home/vagrant/data
    
  SHELL
end
